# Generated by Django 5.0.6 on 2024-07-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created_user',
        ),
    ]
