# Generated by Django 5.2.5 on 2025-08-30 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_list_created_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(blank=True, choices=[('Important', 'Important'), ('Not Important', 'Not Important')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='task_heading',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
